- hosts: workers
  tasks:
    - name: join cluster
      shell: "{{ hostvars[groups['masters'][0]]['join_command'] }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
